version: '1'
services:
  application:
    image: jwt-auth
    container_name: jwt-auth
    depends_on: {mysql-container}
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/jwtauth
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jwtauth
    ports:
      - "3306:3306"